In [4]:
import pandas as pd 
data_1 = pd.read_csv("CD_DATASET.csv")
data_1.head()

              main_name   CD  SW_%  KW_%  LF_%  ST_%      Time    Volume
0  CD + 40% SW + 60% KW  Yes  40.0  60.0   0.0   0.0  0.000000  0.000000
1  CD + 40% SW + 60% KW  Yes  40.0  60.0   0.0   0.0  0.000943  1.920143
2  CD + 40% SW + 60% KW  Yes  40.0  60.0   0.0   0.0  0.003599  2.072750
3  CD + 40% SW + 60% KW  Yes  40.0  60.0   0.0   0.0  0.006423  2.225339
4  CD + 40% SW + 60% KW  Yes  40.0  60.0   0.0   0.0  0.009411  2.377911

In [16]:
data2 = pd.read_csv("CD_BY_DATASET.csv")
data2.drop(columns=['CD_%', 'BY_%'], inplace=True)
data2.head()

,main_name,CD + BY,SW_%,KW_%,LF_%,ST_%,Time,Volume
0,CD + BY + 40% SW + 60% KW,Yes,40.0,60.0,0.0,0.0,0.000000,0.000000
1,CD + BY + 40% SW + 60% KW,Yes,40.0,60.0,0.0,0.0,0.287003,34.742308
2,CD + BY + 40% SW + 60% KW,Yes,40.0,60.0,0.0,0.0,0.288292,34.947740
3,CD + BY + 40% SW + 60% KW,Yes,40.0,60.0,0.0,0.0,0.289652,35.153170
4,CD + BY + 40% SW + 60% KW,Yes,40.0,60.0,0.0,0.0,0.291082,35.358599

In [6]:
data3 = pd.read_csv("BY_DATASET.csv")
data3.head()

              main_name   BY  SW_%  KW_%  LF_%  ST_%      Time     Volume
0  BY + 40% SW + 60% KW  Yes  40.0  60.0   0.0   0.0  0.000000   0.000000
1  BY + 40% SW + 60% KW  Yes  40.0  60.0   0.0   0.0  0.198553  38.298758
2  BY + 40% SW + 60% KW  Yes  40.0  60.0   0.0   0.0  0.201217  38.444227
3  BY + 40% SW + 60% KW  Yes  40.0  60.0   0.0   0.0  0.203875  38.589697
4  BY + 40% SW + 60% KW  Yes  40.0  60.0   0.0   0.0  0.206527  38.735166

In [17]:
data_1.columns

Index(['main_name', 'CD', 'SW_%', 'KW_%', 'LF_%', 'ST_%', 'Time', 'Volume'], dtype='object')

In [18]:
data2.columns

Index(['main_name', 'CD + BY', 'SW_%', 'KW_%', 'LF_%', 'ST_%', 'Time',
       'Volume'],
      dtype='object')

In [19]:
data3.columns

Index(['main_name', 'BY', 'SW_%', 'KW_%', 'LF_%', 'ST_%', 'Time', 'Volume'], dtype='object')

In [25]:
import pandas as pd

# Load the three datasets
by_df = pd.read_csv("BY_DATASET.csv")
cd_df = pd.read_csv("CD_DATASET.csv")
cdby_df = pd.read_csv("CD_BY_DATASET.csv")

# Drop percentage helper columns from CD+BY dataset (not needed)
cdby_df.drop(columns=["CD_%", "BY_%"], inplace=True)

# Encode indicator columns using only BY and CD
# BY_DATASET: BY=1, CD=0
by_df["BY"] = by_df["BY"].apply(lambda x: 1 if str(x).strip().lower() == "yes" else 0)
by_df["CD"] = 0

# CD_BY_DATASET: if CD+BY is Yes, then both BY=1 and CD=1
cdby_flag = cdby_df["CD + BY"].apply(lambda x: 1 if str(x).strip().lower() == "yes" else 0)
cdby_df["BY"] = cdby_flag
cdby_df["CD"] = cdby_flag
cdby_df.drop(columns=["CD + BY"], inplace=True)

# CD_DATASET: CD=1, BY=0
cd_df["CD"] = cd_df["CD"].apply(lambda x: 1 if str(x).strip().lower() == "yes" else 0)
cd_df["BY"] = 0

# Define a consistent column order (no CD+BY column)
col_order = ["main_name", "BY", "CD", "SW_%", "KW_%", "LF_%", "ST_%", "Time", "Volume"]

merged = pd.concat(
    [by_df[col_order], cdby_df[col_order], cd_df[col_order]],
    ignore_index=True,
)

print(merged.shape)
merged.head(10)

(30802, 9)

              main_name  BY  CD  SW_%  KW_%  LF_%  ST_%      Time     Volume
0  BY + 40% SW + 60% KW   1   0  40.0  60.0   0.0   0.0  0.000000   0.000000
1  BY + 40% SW + 60% KW   1   0  40.0  60.0   0.0   0.0  0.198553  38.298758
2  BY + 40% SW + 60% KW   1   0  40.0  60.0   0.0   0.0  0.201217  38.444227
3  BY + 40% SW + 60% KW   1   0  40.0  60.0   0.0   0.0  0.203875  38.589697
4  BY + 40% SW + 60% KW   1   0  40.0  60.0   0.0   0.0  0.206527  38.735166
5  BY + 40% SW + 60% KW   1   0  40.0  60.0   0.0   0.0  0.209174  38.880636
6  BY + 40% SW + 60% KW   1   0  40.0  60.0   0.0   0.0  0.211816  39.026106
7  BY + 40% SW + 60% KW   1   0  40.0  60.0   0.0   0.0  0.214452  39.171576
8  BY + 40% SW + 60% KW   1   0  40.0  60.0   0.0   0.0  0.217083  39.317046
9  BY + 40% SW + 60% KW   1   0  40.0  60.0   0.0   0.0  0.219708  39.462516

In [21]:
merged.to_csv("MERGED_DATASET.csv", index=False)

In [26]:
import numpy as np

# Material properties from Thesis Tables 4.1 and 4.2
# TS / VS are fractions of wet mass; C / N are fractions of dry mass (TS)
MATERIAL_PROPERTIES = {
    'SW': {'type': 'substrate', 'TS': 0.0767, 'VS': 0.0650, 'C': 0.3079, 'N': 0.0769},
    'KW': {'type': 'substrate', 'TS': 0.0957, 'VS': 0.0840, 'C': 0.4800, 'N': 0.0260},
    'ST': {'type': 'substrate', 'TS': 0.9077, 'VS': 0.7797, 'C': 0.3745, 'N': 0.00412},
    'LF': {'type': 'substrate', 'TS': 0.9073, 'VS': 0.7377, 'C': 0.4810, 'N': 0.0120},
    'CD': {'type': 'inoculum', 'TS': 0.2260, 'VS': 0.1777, 'C': 0.4048, 'N': 0.0137},
    'BY': {'type': 'inoculum', 'TS': 0.7500, 'VS': 0.1800, 'C': 0.4830, 'N': 0.1060},
}


def calculate_wet_masses(substrate_fractions, inoculum_types, total_mass=200.0, target_isr=2.0):
    """Back-calculates wet masses (g) for each component in a 200 g reactor at ISR=2:1 VS."""
    vs_sub = sum(frac * MATERIAL_PROPERTIES[mat]['VS'] for mat, frac in substrate_fractions.items())
    n_inoc = len(inoculum_types)
    vs_inoc = sum((1.0 / n_inoc) * MATERIAL_PROPERTIES[mat]['VS'] for mat in inoculum_types)

    k_ratio = target_isr * vs_sub / vs_inoc
    mass_sub = total_mass / (1 + k_ratio)
    mass_inoc = total_mass - mass_sub

    wet_masses = {mat: mass_sub * frac for mat, frac in substrate_fractions.items()}
    for mat in inoculum_types:
        wet_masses[mat] = mass_inoc / n_inoc
    return wet_masses


def engineer_features(wet_masses):
    """Returns TS%, VS%, C/N ratio, and ISR for a given wet-mass composition."""
    total_wet = sum(wet_masses.values())
    total_ts = total_vs = total_c = total_n = 0.0
    vs_inoc = vs_sub = 0.0

    for mat, mass in wet_masses.items():
        props = MATERIAL_PROPERTIES[mat]
        ts_mass = mass * props['TS']
        vs_mass = mass * props['VS']

        total_ts += ts_mass
        total_vs += vs_mass
        total_c += ts_mass * props['C']
        total_n += ts_mass * props['N']

        if props['type'] == 'inoculum':
            vs_inoc += vs_mass
        else:
            vs_sub += vs_mass

    return {
        'TS_mix_pct': (total_ts / total_wet) * 100,
        'VS_mix_pct': (total_vs / total_wet) * 100,
        'CN_ratio_mix': total_c / total_n if total_n > 0 else 0.0,
        'ISR': vs_inoc / vs_sub if vs_sub > 0 else 0.0,
    }


def row_features(row):
    """Derive feature dict from a single merged-dataset row."""
    # Substrate fractions (% -> fraction)
    substrate_fractions = {}
    for col, mat in [('SW_%', 'SW'), ('KW_%', 'KW'), ('LF_%', 'LF'), ('ST_%', 'ST')]:
        value = row[col]
        if pd.notna(value) and value > 0:
            substrate_fractions[mat] = value / 100.0

    # Inoculum mapping without CD+BY column:
    # BY=1 and CD=1 means both are present.
    inoculum_types = []
    if row['BY'] == 1:
        inoculum_types.append('BY')
    if row['CD'] == 1:
        inoculum_types.append('CD')

    if not substrate_fractions or not inoculum_types:
        return {
            'TS_mix_pct': np.nan,
            'VS_mix_pct': np.nan,
            'CN_ratio_mix': np.nan,
            'ISR': np.nan,
        }

    wet_masses = calculate_wet_masses(substrate_fractions, inoculum_types)
    return engineer_features(wet_masses)


feature_cols = merged.apply(row_features, axis=1, result_type='expand')
merged_fe = pd.concat([merged, feature_cols], axis=1)

print(f"New features added: {list(feature_cols.columns)}")
print(f"Dataset shape: {merged_fe.shape}")
merged_fe.head(10)

New features added: ['TS_mix_pct', 'VS_mix_pct', 'CN_ratio_mix', 'ISR']
Dataset shape: (30802, 13)

,main_name,BY,CD,SW_%,KW_%,LF_%,ST_%,Time,Volume,TS_mix_pct,VS_mix_pct,CN_ratio_mix,ISR
0,BY + 40% SW + 60% KW,1,0,40.0,60.0,0.0,0.0,0.000000,0.000000,39.20012,12.396635,4.829316,2.0
1,BY + 40% SW + 60% KW,1,0,40.0,60.0,0.0,0.0,0.198553,38.298758,39.20012,12.396635,4.829316,2.0
2,BY + 40% SW + 60% KW,1,0,40.0,60.0,0.0,0.0,0.201217,38.444227,39.20012,12.396635,4.829316,2.0
3,BY + 40% SW + 60% KW,1,0,40.0,60.0,0.0,0.0,0.203875,38.589697,39.20012,12.396635,4.829316,2.0
4,BY + 40% SW + 60% KW,1,0,40.0,60.0,0.0,0.0,0.206527,38.735166,39.20012,12.396635,4.829316,2.0
5,BY + 40% SW + 60% KW,1,0,40.0,60.0,0.0,0.0,0.209174,38.880636,39.20012,12.396635,4.829316,2.0
6,BY + 40% SW + 60% KW,1,0,40.0,60.0,0.0,0.0,0.211816,39.026106,39.20012,12.396635,4.829316,2.0
7,BY + 40% SW + 60% KW,1,0,40.0,60.0,0.0,0.0,0.214452,39.171576,39.20012,12.396635,4.829316,2.0
8,BY + 40% SW + 60% KW,1,0,40.0,60.0,0.0,0.0,0.217083,39.317046,39.20012,12.396635,4.829316,2.0
9,BY + 40% SW + 60% KW,1,0,40.0,60.0,0.0,0.0,0.219708,39.462516,39.20012,12.396635,4.829316,2.0

In [24]:
merged.head()

,main_name,BY,CD + BY,CD,SW_%,KW_%,LF_%,ST_%,Time,Volume
0,BY + 40% SW + 60% KW,1,0,0,40.0,60.0,0.0,0.0,0.000000,0.000000
1,BY + 40% SW + 60% KW,1,0,0,40.0,60.0,0.0,0.0,0.198553,38.298758
2,BY + 40% SW + 60% KW,1,0,0,40.0,60.0,0.0,0.0,0.201217,38.444227
3,BY + 40% SW + 60% KW,1,0,0,40.0,60.0,0.0,0.0,0.203875,38.589697
4,BY + 40% SW + 60% KW,1,0,0,40.0,60.0,0.0,0.0,0.206527,38.735166

In [29]:
# Cell 12: remove CD+BY from existing merged_fe only
# Assumes merged_fe already exists from Cell 10
if "CD + BY" in merged_fe.columns:
    # Ensure BY and CD columns exist
    if "BY" not in merged_fe.columns:
        merged_fe["BY"] = 0
    if "CD" not in merged_fe.columns:
        merged_fe["CD"] = 0

    cdby_mask = merged_fe["CD + BY"].fillna(0).eq(1)
    merged_fe.loc[cdby_mask, "BY"] = 1
    merged_fe.loc[cdby_mask, "CD"] = 1
    merged_fe.drop(columns=["CD + BY"], inplace=True)
    print("CD + BY removed from merged_fe; mapped to BY=1 and CD=1.")
else:
    print("No CD + BY column found in merged_fe (nothing to remove).")

print("merged_fe columns:", list(merged_fe.columns))
merged_fe.head()

No CD + BY column found in merged_fe (nothing to remove).
merged_fe columns: ['main_name', 'BY', 'CD', 'SW_%', 'KW_%', 'LF_%', 'ST_%', 'Time', 'Volume', 'TS_mix_pct', 'VS_mix_pct', 'CN_ratio_mix', 'ISR']

,main_name,BY,CD,SW_%,KW_%,LF_%,ST_%,Time,Volume,TS_mix_pct,VS_mix_pct,CN_ratio_mix,ISR
0,BY + 40% SW + 60% KW,1,0,40.0,60.0,0.0,0.0,0.000000,0.000000,39.20012,12.396635,4.829316,2.0
1,BY + 40% SW + 60% KW,1,0,40.0,60.0,0.0,0.0,0.198553,38.298758,39.20012,12.396635,4.829316,2.0
2,BY + 40% SW + 60% KW,1,0,40.0,60.0,0.0,0.0,0.201217,38.444227,39.20012,12.396635,4.829316,2.0
3,BY + 40% SW + 60% KW,1,0,40.0,60.0,0.0,0.0,0.203875,38.589697,39.20012,12.396635,4.829316,2.0
4,BY + 40% SW + 60% KW,1,0,40.0,60.0,0.0,0.0,0.206527,38.735166,39.20012,12.396635,4.829316,2.0

In [32]:
merged_fe.to_csv("MERGED_FINAL.csv", index=False)

In [23]:
merged.to_csv("MERGED FINAL.csv", index=False)