In [ ]:
rename_map = {
    "a.png": "CD + SW.png",
    "b.png": "CD + KW.png",
    "c.png": "CD + 40% SW + 60% KW.png",
    "d.png": "CD + 70% SW + 30% KW.png",
    "e.png": "CD + 68.5% SW + 30% KW + 1.5% LF.png",
    "f.png": "CD + 65% SW + 30% KW + 5% LF.png",
    "g.png": "CD + 62.5% SW + 30% KW + 7.5% LF.png",
    "h.png": "CD + 60% SW + 30% KW + 10% LF.png",
    "i.png": "CD + 68.5% SW + 30% KW + 1.5% ST.png",
    "j.png": "CD + 65% SW + 30% KW + 5% ST.png",
    "k.png": "CD + 60% SW + 30% KW + 10% ST.png"
}
import os 
os.listdir("MY WORK")
#rename files in the directory "MY WORK" according to the rename_map
for old_name, new_name in rename_map.items():
    old_path = os.path.join("MY WORK", old_name)
    new_path = os.path.join("MY WORK", new_name)
    os.rename(old_path, new_path)
os.listdir("MY WORK")

['CD + 40% SW + 60% KW.png',
 'CD + 60% SW + 30% KW + 10% LF.png',
 'CD + 60% SW + 30% KW + 10% ST.png',
 'CD + 62.5% SW + 30% KW + 7.5% LF.png',
 'CD + 65% SW + 30% KW + 5% LF.png',
 'CD + 65% SW + 30% KW + 5% ST.png',
 'CD + 68.5% SW + 30% KW + 1.5% LF.png',
 'CD + 68.5% SW + 30% KW + 1.5% ST.png',
 'CD + 70% SW + 30% KW.png',
 'CD + KW.png',
 'CD + SW.png']

In [2]:
import os
files_to_trace = os.listdir("MY WORK")
files_to_trace.sort()
files_to_trace

['CD + 40% SW + 60% KW.png',
 'CD + 60% SW + 30% KW + 10% LF.png',
 'CD + 60% SW + 30% KW + 10% ST.png',
 'CD + 62.5% SW + 30% KW + 7.5% LF.png',
 'CD + 65% SW + 30% KW + 5% LF.png',
 'CD + 65% SW + 30% KW + 5% ST.png',
 'CD + 68.5% SW + 30% KW + 1.5% LF.png',
 'CD + 68.5% SW + 30% KW + 1.5% ST.png',
 'CD + 70% SW + 30% KW.png',
 'CD + KW.png',
 'CD + SW.png']

In [3]:
files_paths = [os.path.join("MY WORK", file) for file in files_to_trace]
files_paths

['MY WORK\\CD + 40% SW + 60% KW.png',
 'MY WORK\\CD + 60% SW + 30% KW + 10% LF.png',
 'MY WORK\\CD + 60% SW + 30% KW + 10% ST.png',
 'MY WORK\\CD + 62.5% SW + 30% KW + 7.5% LF.png',
 'MY WORK\\CD + 65% SW + 30% KW + 5% LF.png',
 'MY WORK\\CD + 65% SW + 30% KW + 5% ST.png',
 'MY WORK\\CD + 68.5% SW + 30% KW + 1.5% LF.png',
 'MY WORK\\CD + 68.5% SW + 30% KW + 1.5% ST.png',
 'MY WORK\\CD + 70% SW + 30% KW.png',
 'MY WORK\\CD + KW.png',
 'MY WORK\\CD + SW.png']

In [4]:
#remove .png from file names
file_names_without_extension = [os.path.splitext(file)[0] for file in files_to_trace]
file_names_without_extension

['CD + 40% SW + 60% KW',
 'CD + 60% SW + 30% KW + 10% LF',
 'CD + 60% SW + 30% KW + 10% ST',
 'CD + 62.5% SW + 30% KW + 7.5% LF',
 'CD + 65% SW + 30% KW + 5% LF',
 'CD + 65% SW + 30% KW + 5% ST',
 'CD + 68.5% SW + 30% KW + 1.5% LF',
 'CD + 68.5% SW + 30% KW + 1.5% ST',
 'CD + 70% SW + 30% KW',
 'CD + KW',
 'CD + SW']

In [41]:
import graphtrace
inedx = 11
import matplotlib.pyplot as plt
file = files_paths[inedx]
#show preview of file
plt.imshow(plt.imread(file))
plt.show()

IndexError: list index out of range

In [40]:

# One-liner
# df = graphtrace.extract("test.png", x_range=(0, 12), y_range=(0, 7), n_points=100)
gt = graphtrace.GraphTrace(file)
gt.preprocess()                                  # optional
gt.calibrate(x_range=(0, 20), y_range=(0,80))   # interactive clicks
gt.trace(mode="click")
points = gt.sample(n=1000)
gt.to_csv(f"{file_names_without_extension[inedx]}.csv", x_label="Time", y_label="Volume")
gt.preview()

[graphtrace] Preprocessing image...
[graphtrace] Applied auto preprocessing (contrast + denoise).
[graphtrace] Opening interactive calibration window...
[graphtrace] Zoom/pan with the toolbar. Press 'z' to undo the last click.
[graphtrace] Jupyter detected — attempting to use interactive backend.
[graphtrace] Falling back to %matplotlib tk backend.
[graphtrace] X-end clicked at pixel (934, 551)
[graphtrace] Y-end clicked at pixel (193, 65)
[graphtrace] Origin auto-computed from X-end and Y-end intersection
[graphtrace] Origin auto-computed at pixel (193, 551)
[graphtrace] Seed #1 at pixel (193, 545)
[graphtrace] Seed #2 at pixel (202, 441)
[graphtrace] Seed #3 at pixel (210, 408)
[graphtrace] Seed #4 at pixel (221, 383)
[graphtrace] Seed #5 at pixel (229, 366)
[graphtrace] Seed #6 at pixel (248, 334)
[graphtrace] Seed #7 at pixel (278, 300)
[graphtrace] Seed #8 at pixel (305, 281)
[graphtrace] Seed #9 at pixel (361, 253)
[graphtrace] Seed #10 at pixel (414, 234)
[graphtrace] Seed #11 at pixel (482, 215)
[graphtrace] Seed #12 at pixel (446, 222)
[graphtrace] Seed #13 at pixel (520, 206)
[graphtrace] Seed #14 at pixel (260, 321)
[graphtrace] Seed #15 at pixel (314, 276)
[graphtrace] Seed #16 at pixel (324, 270)
[graphtrace] Seed #17 at pixel (333, 265)
[graphtrace] Seed #18 at pixel (344, 261)
[graphtrace] Seed #19 at pixel (351, 257)
[graphtrace] Seed #20 at pixel (528, 204)
[graphtrace] Seed #21 at pixel (540, 199)
[graphtrace] Seed #22 at pixel (551, 199)
[graphtrace] Seed #23 at pixel (561, 198)
[graphtrace] Seed #24 at pixel (566, 197)
[graphtrace] Seed #25 at pixel (575, 195)
[graphtrace] Seed #26 at pixel (584, 194)
[graphtrace] Seed #27 at pixel (592, 192)
[graphtrace] Seed #28 at pixel (602, 190)
[graphtrace] Seed #29 at pixel (622, 185)
[graphtrace] Seed #30 at pixel (651, 181)
[graphtrace] Seed #31 at pixel (670, 178)
[graphtrace] Seed #32 at pixel (688, 177)
[graphtrace] Seed #33 at pixel (703, 175)
[graphtrace] Seed #34 at pixel (731, 170)
[graphtrace] Seed #35 at pixel (758, 168)
[graphtrace] Seed #36 at pixel (787, 165)
[graphtrace] Seed #37 at pixel (817, 162)
[graphtrace] Seed #38 at pixel (844, 158)
[graphtrace] Seed #39 at pixel (871, 157)
[graphtrace] Calibration complete: 39 seed(s), 0 bg sample(s).
[graphtrace] Tracing curve (mode='click')...
[graphtrace] Click mode: using 39 seed clicks as data points.
[graphtrace] Trace complete: discrete, 39 path pixels found.
[graphtrace] Sampling 1000 points via arc-length spline interpolation...
[graphtrace] Sampled 1000 data-space points.
[graphtrace] Exported 1000 points to CD + SW.csv
[graphtrace] Previewing 1000 extracted points overlaid on original image.

In [44]:
import pandas as pd
data=pd.read_csv("CD + 40% SW + 60% KW.csv")
data.head()

       Time    Volume
0 -0.016523 -0.065434
1 -0.016412  0.087419
2 -0.016080  0.240252
3 -0.015532  0.393066
4 -0.014772  0.545859

In [48]:
import pandas as pd
import re
import os

files_names = [
    'CD + 40% SW + 60% KW',
    'CD + 60% SW + 30% KW + 10% LF',
    'CD + 60% SW + 30% KW + 10% ST',
    'CD + 62.5% SW + 30% KW + 7.5% LF',
    'CD + 65% SW + 30% KW + 5% LF',
    'CD + 65% SW + 30% KW + 5% ST',
    'CD + 68.5% SW + 30% KW + 1.5% LF',
    'CD + 68.5% SW + 30% KW + 1.5% ST',
    'CD + 70% SW + 30% KW',
    'CD + KW',
    'CD + SW'
]

def parse_filename(filename):
    """
    Parses the filename to extract categorical presence and numerical percentages.
    """
    features = {'main_name': filename, 'CD': 'No'}
    
    # Split the string by the '+' delimiter
    parts = [p.strip() for p in filename.split('+')]
    
    for part in parts:
        if part == 'CD':
            features['CD'] = 'Yes'
        else:
            # Regex to match explicit percentages (e.g., '62.5% SW')
            pct_match = re.match(r'(\d+\.?\d*)%\s*([A-Za-z]+)', part)
            if pct_match:
                val, mat = pct_match.groups()
                features[f'{mat}_%'] = float(val)
            else:
                # Match implied 100% additive components (e.g., 'KW' in 'CD + KW')
                mat_match = re.match(r'([A-Za-z]+)', part)
                if mat_match:
                    mat = mat_match.group(1)
                    features[f'{mat}_%'] = 100.0 
                    
    return features

dataframes = []

for name in files_names:
    csv_path = f"{name}.csv"
    
    # In a real run, you'd want to handle FileNotFoundError appropriately.
    if os.path.exists(csv_path):
        df = pd.read_csv(csv_path)
        
        parsed_data = parse_filename(name)
        
        # Broadcast the parsed scalar values to the entire DataFrame
        for col_name, value in parsed_data.items():
            df[col_name] = value
            
        dataframes.append(df)
    else:
        print(f"Skipping {csv_path} - File not found.")

# Concatenate into a single master dataset if files were found
if dataframes:
    master_df = pd.concat(dataframes, ignore_index=True)
    
    # Any material not present in a specific file will yield NaN. 
    # Impute these with 0.0 for the percentage columns.
    percentage_cols = [c for c in master_df.columns if c.endswith('_%')]
    master_df[percentage_cols] = master_df[percentage_cols].fillna(0.0)
    
    # Display the unique generated features to verify extraction
    print(master_df.drop_duplicates(subset=['main_name'])[
        ['main_name', 'CD'] + percentage_cols
    ])
    
    # master_df.to_csv('combined_extracted_data.csv', index=False)

                              main_name   CD   SW_%   KW_%  LF_%  ST_%
0                  CD + 40% SW + 60% KW  Yes   40.0   60.0   0.0   0.0
1000      CD + 60% SW + 30% KW + 10% LF  Yes   60.0   30.0  10.0   0.0
2000      CD + 60% SW + 30% KW + 10% ST  Yes   60.0   30.0   0.0  10.0
3000   CD + 62.5% SW + 30% KW + 7.5% LF  Yes   62.5   30.0   7.5   0.0
4000       CD + 65% SW + 30% KW + 5% LF  Yes   65.0   30.0   5.0   0.0
5000       CD + 65% SW + 30% KW + 5% ST  Yes   65.0   30.0   0.0   5.0
6000   CD + 68.5% SW + 30% KW + 1.5% LF  Yes   68.5   30.0   1.5   0.0
7000   CD + 68.5% SW + 30% KW + 1.5% ST  Yes   68.5   30.0   0.0   1.5
8000               CD + 70% SW + 30% KW  Yes   70.0   30.0   0.0   0.0
9000                            CD + KW  Yes    0.0  100.0   0.0   0.0
10000                           CD + SW  Yes  100.0    0.0   0.0   0.0

In [49]:
import pandas as pd

# Assuming the concatenated dataframe from the previous step is named 'master_df'
# and contains 'Time', 'Volume', 'main_name', plus the metadata columns.

# 1. Filter out rows with negative Time or Volume. 
# Using (Time >= 0) & (Volume >= 0) removes a row if *either* is negative. 
# If you strictly meant omitting only when *both* are negative concurrently, 
# you would use: master_df[~((master_df['Time'] < 0) & (master_df['Volume'] < 0))]
master_df = master_df[(master_df['Time'] >= 0) & (master_df['Volume'] >= 0)].copy()

# 2. Isolate the metadata columns (everything except Time and Volume)
meta_cols = [col for col in master_df.columns if col not in ['Time', 'Volume']]

# 3. Extract the unique metadata mapping for each 'main_name'
# This ensures the new 0,0 rows inherit the correct CD status and percentages
zero_rows = master_df[meta_cols].drop_duplicates(subset=['main_name']).copy()

# 4. Assign Time = 0 and Volume = 0
zero_rows['Time'] = 0.0
zero_rows['Volume'] = 0.0

# 5. Concatenate the zero-initialized rows with the filtered dataset
master_df = pd.concat([zero_rows, master_df], ignore_index=True)

# 6. Drop potential duplicates (in case a Time=0, Volume=0 row already existed)
# and sort the dataframe to maintain chronological order per file
master_df = master_df.drop_duplicates().sort_values(by=['main_name', 'Time']).reset_index(drop=True)

# Verify the insertion
print(master_df.groupby('main_name').head(2))

                             main_name   CD   SW_%   KW_%  LF_%  ST_%  \
0                 CD + 40% SW + 60% KW  Yes   40.0   60.0   0.0   0.0
1                 CD + 40% SW + 60% KW  Yes   40.0   60.0   0.0   0.0
988      CD + 60% SW + 30% KW + 10% LF  Yes   60.0   30.0  10.0   0.0
989      CD + 60% SW + 30% KW + 10% LF  Yes   60.0   30.0  10.0   0.0
1989     CD + 60% SW + 30% KW + 10% ST  Yes   60.0   30.0   0.0  10.0
1990     CD + 60% SW + 30% KW + 10% ST  Yes   60.0   30.0   0.0  10.0
2990  CD + 62.5% SW + 30% KW + 7.5% LF  Yes   62.5   30.0   7.5   0.0
2991  CD + 62.5% SW + 30% KW + 7.5% LF  Yes   62.5   30.0   7.5   0.0
3951      CD + 65% SW + 30% KW + 5% LF  Yes   65.0   30.0   5.0   0.0
3952      CD + 65% SW + 30% KW + 5% LF  Yes   65.0   30.0   5.0   0.0
4905      CD + 65% SW + 30% KW + 5% ST  Yes   65.0   30.0   0.0   5.0
4906      CD + 65% SW + 30% KW + 5% ST  Yes   65.0   30.0   0.0   5.0
5825  CD + 68.5% SW + 30% KW + 1.5% LF  Yes   68.5   30.0   1.5   0.0
5826  CD + 68.5% SW + 30% KW + 1.5% LF  Yes   68.5   30.0   1.5   0.0
6826  CD + 68.5% SW + 30% KW + 1.5% ST  Yes   68.5   30.0   0.0   1.5
6827  CD + 68.5% SW + 30% KW + 1.5% ST  Yes   68.5   30.0   0.0   1.5
7820              CD + 70% SW + 30% KW  Yes   70.0   30.0   0.0   0.0
7821              CD + 70% SW + 30% KW  Yes   70.0   30.0   0.0   0.0
8821                           CD + KW  Yes    0.0  100.0   0.0   0.0
8822                           CD + KW  Yes    0.0  100.0   0.0   0.0
9812                           CD + SW  Yes  100.0    0.0   0.0   0.0
9813                           CD + SW  Yes  100.0    0.0   0.0   0.0

          Time     Volume
0     0.000000   0.000000
1     0.000943   1.920143
988   0.000000   0.000000
989   0.134992   6.578757
1989  0.000000   0.000000
1990  0.284753   9.950818
2990  0.000000   0.000000
2991  0.001326   3.515928
3951  0.000000   0.000000
3952  0.001002   4.614617
4905  0.000000   0.000000
4906  0.000390   3.630792
5825  0.000000   0.000000
5826  0.277778  12.195122
6826  0.000000   0.000000
6827  0.001983   3.623021
7820  0.000000   0.000000
7821  0.032146   2.172701
8821  0.000000   0.000000
8822  0.005135   1.455268
9812  0.000000   0.000000
9813  0.000049   2.974313

In [51]:
master_df.head()

              main_name   CD  SW_%  KW_%  LF_%  ST_%      Time    Volume
0  CD + 40% SW + 60% KW  Yes  40.0  60.0   0.0   0.0  0.000000  0.000000
1  CD + 40% SW + 60% KW  Yes  40.0  60.0   0.0   0.0  0.000943  1.920143
2  CD + 40% SW + 60% KW  Yes  40.0  60.0   0.0   0.0  0.003599  2.072750
3  CD + 40% SW + 60% KW  Yes  40.0  60.0   0.0   0.0  0.006423  2.225339
4  CD + 40% SW + 60% KW  Yes  40.0  60.0   0.0   0.0  0.009411  2.377911

In [52]:
master_df.to_csv("CD_DATASET.csv" , index=False)