In [31]:
import os

rename_map = {
    "a.png": "CD + BY + SW.png",
    "b.png": "CD + BY + KW.png",
    "c.png": "CD + BY + 40% SW + 60% KW.png",
    "d.png": "CD + BY + 70% SW + 30% KW.png",
    "e.png": "CD + BY + 68.5% SW + 30% KW + 1.5% LF.png",
    "f.png": "CD + BY + 65% SW + 30% KW + 5% LF.png",
    "g.png": "CD + BY + 60% SW + 30% KW + 10% LF.png",
    "h.png": "CD + BY + 68.5% SW + 30% KW + 1.5% ST.png",
    "i.png": "CD + BY + 65% SW + 30% KW + 5% ST.png",
    "j.png": "CD + BY + 60% SW + 30% KW + 10% ST.png"
}

directory = "MY WORK"

# Rename files in the directory
for old_name, new_name in rename_map.items():
    old_path = os.path.join(directory, old_name)
    new_path = os.path.join(directory, new_name)
    
    # Check if the file exists before renaming to avoid errors
    if os.path.exists(old_path):
        os.rename(old_path, new_path)
        print(f"Renamed: {old_name} -> {new_name}")
    else:
        print(f"Skipped: {old_name} not found")

print(os.listdir(directory))

Renamed: a.png -> CD + BY + SW.png
Renamed: b.png -> CD + BY + KW.png
Renamed: c.png -> CD + BY + 40% SW + 60% KW.png
Renamed: d.png -> CD + BY + 70% SW + 30% KW.png
Renamed: e.png -> CD + BY + 68.5% SW + 30% KW + 1.5% LF.png
Renamed: f.png -> CD + BY + 65% SW + 30% KW + 5% LF.png
Renamed: g.png -> CD + BY + 60% SW + 30% KW + 10% LF.png
Renamed: h.png -> CD + BY + 68.5% SW + 30% KW + 1.5% ST.png
Renamed: i.png -> CD + BY + 65% SW + 30% KW + 5% ST.png
Renamed: j.png -> CD + BY + 60% SW + 30% KW + 10% ST.png
['A', 'CD + BY + 40% SW + 60% KW.png', 'CD + BY + 60% SW + 30% KW + 10% LF.png', 'CD + BY + 60% SW + 30% KW + 10% ST.png', 'CD + BY + 65% SW + 30% KW + 5% LF.png', 'CD + BY + 65% SW + 30% KW + 5% ST.png', 'CD + BY + 68.5% SW + 30% KW + 1.5% LF.png', 'CD + BY + 68.5% SW + 30% KW + 1.5% ST.png', 'CD + BY + 70% SW + 30% KW.png', 'CD + BY + KW.png', 'CD + BY + SW.png', 'JUST BY']

In [33]:
import os
files_to_trace = os.listdir("MY WORK")
files_to_trace.sort()
files_to_trace

['CD + BY + 40% SW + 60% KW.png',
 'CD + BY + 60% SW + 30% KW + 10% LF.png',
 'CD + BY + 60% SW + 30% KW + 10% ST.png',
 'CD + BY + 65% SW + 30% KW + 5% LF.png',
 'CD + BY + 65% SW + 30% KW + 5% ST.png',
 'CD + BY + 68.5% SW + 30% KW + 1.5% LF.png',
 'CD + BY + 68.5% SW + 30% KW + 1.5% ST.png',
 'CD + BY + 70% SW + 30% KW.png',
 'CD + BY + KW.png',
 'CD + BY + SW.png']

In [34]:
files_paths = [os.path.join("MY WORK", file) for file in files_to_trace]
files_paths

['MY WORK\\CD + BY + 40% SW + 60% KW.png',
 'MY WORK\\CD + BY + 60% SW + 30% KW + 10% LF.png',
 'MY WORK\\CD + BY + 60% SW + 30% KW + 10% ST.png',
 'MY WORK\\CD + BY + 65% SW + 30% KW + 5% LF.png',
 'MY WORK\\CD + BY + 65% SW + 30% KW + 5% ST.png',
 'MY WORK\\CD + BY + 68.5% SW + 30% KW + 1.5% LF.png',
 'MY WORK\\CD + BY + 68.5% SW + 30% KW + 1.5% ST.png',
 'MY WORK\\CD + BY + 70% SW + 30% KW.png',
 'MY WORK\\CD + BY + KW.png',
 'MY WORK\\CD + BY + SW.png']

In [35]:
#remove .png from file names
file_names_without_extension = [os.path.splitext(file)[0] for file in files_to_trace]
file_names_without_extension

['CD + BY + 40% SW + 60% KW',
 'CD + BY + 60% SW + 30% KW + 10% LF',
 'CD + BY + 60% SW + 30% KW + 10% ST',
 'CD + BY + 65% SW + 30% KW + 5% LF',
 'CD + BY + 65% SW + 30% KW + 5% ST',
 'CD + BY + 68.5% SW + 30% KW + 1.5% LF',
 'CD + BY + 68.5% SW + 30% KW + 1.5% ST',
 'CD + BY + 70% SW + 30% KW',
 'CD + BY + KW',
 'CD + BY + SW']

In [61]:
import graphtrace
inedx = 10
import matplotlib.pyplot as plt
file = files_paths[inedx]
#show preview of file
plt.imshow(plt.imread(file))
plt.show()

IndexError: list index out of range

In [60]:

# One-liner
# df = graphtrace.extract("test.png", x_range=(0, 12), y_range=(0, 7), n_points=100)
gt = graphtrace.GraphTrace(file)
gt.preprocess()                                  # optional
gt.calibrate(x_range=(0,25), y_range=(0,180))   # interactive clicks
gt.trace(mode="click")
points = gt.sample(n=1000)
gt.to_csv(f"{file_names_without_extension[inedx]}.csv", x_label="Time", y_label="Volume")
gt.preview()

[graphtrace] Preprocessing image...
[graphtrace] Applied auto preprocessing (contrast + denoise).
[graphtrace] Opening interactive calibration window...
[graphtrace] Zoom/pan with the toolbar. Press 'z' to undo the last click.
[graphtrace] Jupyter detected — attempting to use interactive backend.
[graphtrace] Falling back to %matplotlib tk backend.
[graphtrace] X-end clicked at pixel (1069, 666)
[graphtrace] Y-end clicked at pixel (162, 45)
[graphtrace] Origin auto-computed from X-end and Y-end intersection
[graphtrace] Origin auto-computed at pixel (162, 666)
[graphtrace] Seed #1 at pixel (163, 667)
[graphtrace] Seed #2 at pixel (170, 568)
[graphtrace] Seed #3 at pixel (201, 481)
[graphtrace] Seed #4 at pixel (250, 403)
[graphtrace] Seed #5 at pixel (426, 317)
[graphtrace] Seed #6 at pixel (948, 230)
[graphtrace] Calibration complete: 6 seed(s), 0 bg sample(s).
[graphtrace] Tracing curve (mode='click')...
[graphtrace] Click mode: using 6 seed clicks as data points.
[graphtrace] Trace complete: discrete, 6 path pixels found.
[graphtrace] Sampling 1000 points via arc-length spline interpolation...
[graphtrace] Sampled 1000 data-space points.
[graphtrace] Exported 1000 points to CD + BY + SW.csv
[graphtrace] Previewing 1000 extracted points overlaid on original image.

In [62]:
import pandas as pd
data=pd.read_csv("CD + BY + 40% SW + 60% KW.csv")
data.head()

       Time     Volume
0  0.287003  34.742308
1  0.288292  34.947740
2  0.289652  35.153170
3  0.291082  35.358599
4  0.292580  35.564026

In [69]:
import pandas as pd
import re
import os

files_names = [
    'CD + BY + 40% SW + 60% KW',
    'CD + BY + 60% SW + 30% KW + 10% LF',
    'CD + BY + 60% SW + 30% KW + 10% ST',
    'CD + BY + 62.5% SW + 30% KW + 7.5% LF',
    'CD + BY + 65% SW + 30% KW + 5% LF',
    'CD + BY + 65% SW + 30% KW + 5% ST',
    'CD + BY + 68.5% SW + 30% KW + 1.5% LF',
    'CD + BY + 68.5% SW + 30% KW + 1.5% ST',
    'CD + BY + 70% SW + 30% KW',
    'CD + BY + KW',
    'CD + BY + SW'
]

def parse_filename(filename):
    """
    Parses the filename to extract categorical presence and numerical percentages.
    """
    features = {'main_name': filename, 'CD + BY': 'No'}
    
    # Split the string CD + BY the '+' delimiter
    parts = [p.strip() for p in filename.split('+')]
    
    for part in parts:
        features['CD + BY'] = 'Yes'
        if part == 'CD + BY':
            features['CD + BY'] = 'Yes'
        else:
            # Regex to match explicit percentages (e.g., '62.5% SW')
            pct_match = re.match(r'(\d+\.?\d*)%\s*([A-Za-z]+)', part)
            if pct_match:
                val, mat = pct_match.groups()
                features[f'{mat}_%'] = float(val)
            else:
                # Match implied 100% additive components (e.g., 'KW' in 'CD + BY + KW')
                mat_match = re.match(r'([A-Za-z]+)', part)
                if mat_match:
                    mat = mat_match.group(1)
                    features[f'{mat}_%'] = 100.0 
                    
    return features

dataframes = []

for name in files_names:
    csv_path = f"{name}.csv"
    
    # In a real run, you'd want to handle FileNotFoundError appropriately.
    if os.path.exists(csv_path):
        df = pd.read_csv(csv_path)
        
        parsed_data = parse_filename(name)
        
        # Broadcast the parsed scalar values to the entire DataFrame
        for col_name, value in parsed_data.items():
            df[col_name] = value
            
        dataframes.append(df)
    else:
        print(f"Skipping {csv_path} - File not found.")

# Concatenate into a single master dataset if files were found
if dataframes:
    master_df = pd.concat(dataframes, ignore_index=True)
    
    # Any material not present in a specific file will yield NaN. 
    # Impute these with 0.0 for the percentage columns.
    percentage_cols = [c for c in master_df.columns if c.endswith('_%')]
    master_df[percentage_cols] = master_df[percentage_cols].fillna(0.0)
    
    # Display the unique generated features to verify extraction
    print(master_df.drop_duplicates(subset=['main_name'])[
        ['main_name', 'CD + BY'] + percentage_cols
    ])
    
    # master_df.to_csv('combined_extracted_data.csv', index=False)

Skipping CD + BY + 62.5% SW + 30% KW + 7.5% LF.csv - File not found.
                                  main_name CD + BY   CD_%   BY_%   SW_%  \
0                 CD + BY + 40% SW + 60% KW     Yes  100.0  100.0   40.0
1000     CD + BY + 60% SW + 30% KW + 10% LF     Yes  100.0  100.0   60.0
2000     CD + BY + 60% SW + 30% KW + 10% ST     Yes  100.0  100.0   60.0
3000      CD + BY + 65% SW + 30% KW + 5% LF     Yes  100.0  100.0   65.0
4000      CD + BY + 65% SW + 30% KW + 5% ST     Yes  100.0  100.0   65.0
5000  CD + BY + 68.5% SW + 30% KW + 1.5% LF     Yes  100.0  100.0   68.5
6000  CD + BY + 68.5% SW + 30% KW + 1.5% ST     Yes  100.0  100.0   68.5
7000              CD + BY + 70% SW + 30% KW     Yes  100.0  100.0   70.0
8000                           CD + BY + KW     Yes  100.0  100.0    0.0
9000                           CD + BY + SW     Yes  100.0  100.0  100.0

       KW_%  LF_%  ST_%
0      60.0   0.0   0.0
1000   30.0  10.0   0.0
2000   30.0   0.0  10.0
3000   30.0   5.0   0.0
4000   30.0   0.0   5.0
5000   30.0   1.5   0.0
6000   30.0   0.0   1.5
7000   30.0   0.0   0.0
8000  100.0   0.0   0.0
9000    0.0   0.0   0.0

In [70]:
import pandas as pd

# Assuming the concatenated dataframe from the previous step is named 'master_df'
# and contains 'Time', 'Volume', 'main_name', plus the metadata columns.

# 1. Filter out rows with negative Time or Volume. 
# Using (Time >= 0) & (Volume >= 0) removes a row if *either* is negative. 
# If you strictly meant omitting only when *both* are negative concurrently, 
# you would use: master_df[~((master_df['Time'] < 0) & (master_df['Volume'] < 0))]
master_df = master_df[(master_df['Time'] >= 0) & (master_df['Volume'] >= 0)].copy()

# 2. Isolate the metadata columns (everything except Time and Volume)
meta_cols = [col for col in master_df.columns if col not in ['Time', 'Volume']]

# 3. Extract the unique metadata mapping for each 'main_name'
# This ensures the new 0,0 rows inherit the correct CD + BY status and percentages
zero_rows = master_df[meta_cols].drop_duplicates(subset=['main_name']).copy()

# 4. Assign Time = 0 and Volume = 0
zero_rows['Time'] = 0.0
zero_rows['Volume'] = 0.0

# 5. Concatenate the zero-initialized rows with the filtered dataset
master_df = pd.concat([zero_rows, master_df], ignore_index=True)

# 6. Drop potential duplicates (in case a Time=0, Volume=0 row already existed)
# and sort the dataframe to maintain chronological order per file
master_df = master_df.drop_duplicates().sort_values(by=['main_name', 'Time']).reset_index(drop=True)

# Verify the insertion
print(master_df.groupby('main_name').head(2))

                                  main_name CD + BY   CD_%   BY_%   SW_%  \
0                 CD + BY + 40% SW + 60% KW     Yes  100.0  100.0   40.0
1                 CD + BY + 40% SW + 60% KW     Yes  100.0  100.0   40.0
1001     CD + BY + 60% SW + 30% KW + 10% LF     Yes  100.0  100.0   60.0
1002     CD + BY + 60% SW + 30% KW + 10% LF     Yes  100.0  100.0   60.0
2002     CD + BY + 60% SW + 30% KW + 10% ST     Yes  100.0  100.0   60.0
2003     CD + BY + 60% SW + 30% KW + 10% ST     Yes  100.0  100.0   60.0
3003      CD + BY + 65% SW + 30% KW + 5% LF     Yes  100.0  100.0   65.0
3004      CD + BY + 65% SW + 30% KW + 5% LF     Yes  100.0  100.0   65.0
4004      CD + BY + 65% SW + 30% KW + 5% ST     Yes  100.0  100.0   65.0
4005      CD + BY + 65% SW + 30% KW + 5% ST     Yes  100.0  100.0   65.0
5005  CD + BY + 68.5% SW + 30% KW + 1.5% LF     Yes  100.0  100.0   68.5
5006  CD + BY + 68.5% SW + 30% KW + 1.5% LF     Yes  100.0  100.0   68.5
6006  CD + BY + 68.5% SW + 30% KW + 1.5% ST     Yes  100.0  100.0   68.5
6007  CD + BY + 68.5% SW + 30% KW + 1.5% ST     Yes  100.0  100.0   68.5
7007              CD + BY + 70% SW + 30% KW     Yes  100.0  100.0   70.0
7008              CD + BY + 70% SW + 30% KW     Yes  100.0  100.0   70.0
8008                           CD + BY + KW     Yes  100.0  100.0    0.0
8009                           CD + BY + KW     Yes  100.0  100.0    0.0
9009                           CD + BY + SW     Yes  100.0  100.0  100.0
9010                           CD + BY + SW     Yes  100.0  100.0  100.0

       KW_%  LF_%  ST_%      Time     Volume
0      60.0   0.0   0.0  0.000000   0.000000
1      60.0   0.0   0.0  0.287003  34.742308
1001   30.0  10.0   0.0  0.000000   0.000000
1002   30.0  10.0   0.0  0.320503  13.904456
2002   30.0   0.0  10.0  0.000000   0.000000
2003   30.0   0.0  10.0  0.190182  14.560600
3003   30.0   5.0   0.0  0.000000   0.000000
3004   30.0   5.0   0.0  0.132559  31.037281
4004   30.0   0.0   5.0  0.000000   0.000000
4005   30.0   0.0   5.0  0.218009  27.076152
5005   30.0   1.5   0.0  0.000000   0.000000
5006   30.0   1.5   0.0  0.279352  27.638943
6006   30.0   0.0   1.5  0.000000   0.000000
6007   30.0   0.0   1.5  0.141183  14.506354
7007   30.0   0.0   0.0  0.000000   0.000000
7008   30.0   0.0   0.0  0.019385   2.173292
8008  100.0   0.0   0.0  0.000000   0.000000
8009  100.0   0.0   0.0  0.036545   1.224268
9009    0.0   0.0   0.0  0.000000   0.000000
9010    0.0   0.0   0.0  0.027364   0.007533

In [71]:
master_df.head()

,main_name,CD + BY,CD_%,BY_%,SW_%,KW_%,LF_%,ST_%,Time,Volume
0,CD + BY + 40% SW + 60% KW,Yes,100.0,100.0,40.0,60.0,0.0,0.0,0.000000,0.000000
1,CD + BY + 40% SW + 60% KW,Yes,100.0,100.0,40.0,60.0,0.0,0.0,0.287003,34.742308
2,CD + BY + 40% SW + 60% KW,Yes,100.0,100.0,40.0,60.0,0.0,0.0,0.288292,34.947740
3,CD + BY + 40% SW + 60% KW,Yes,100.0,100.0,40.0,60.0,0.0,0.0,0.289652,35.153170
4,CD + BY + 40% SW + 60% KW,Yes,100.0,100.0,40.0,60.0,0.0,0.0,0.291082,35.358599

In [73]:
master_df.to_csv("CD_BY_DATASET.csv" , index=False)